export const lessonCategory = [
  { icon: "/png/akustik.png", label: "Gitar Akustik", value: "gitar" },
  { icon: "/png/bass.png", label: "Gitar Bass", value: "bass" },
  { icon: "/png/gitar-elektrik.png", label: "Gitar Elektrik", value: "g-elektrik" },
  { icon: "/png/biola.png", label: "Biola", value: "biola" },
  { icon: "/png/vocal.png", label: "Vokal", value: "vokal" },
  { icon: "/png/piano.png", label: "Piano", value: "piano" },
  { icon: "/png/drum.png", label: "Drum", value: "drum" },
  { icon: "/png/drum-elektrik.png", label: "Drum Elektrik", value: "d-elektrik" },
  { icon: "/png/saxophone.png", label: "Saxophone", value: "saxo" },
  { icon: "/png/seruling.png", label: "Flute", value: "flute" },
];

export const teacherList = [
  {
    id: "1",
    image: "https://via.placeholder.com/150",
    name: "John Doe",
    location: "New York, NY",
    rating_total: "4.5",
    tags: [{ label: "Guitar" }, { label: "Beginner" }],
    short: "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Aenean ut lectus dui. Nullam vulputate commodo euismod. In sodales imperdiet nisl vel scelerisque.",
    bio: "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Aenean ut lectus dui. Nullam vulputate commodo euismod. In sodales imperdiet nisl vel scelerisque. Duis venenatis fermentum lacinia. Quisque in porta dui, vel dictum odio. Phasellus ac tellus non neque pellentesque laoreet.\n \nAenean sit amet elit sit amet sem ornare blandit. Quisque in augue id ligula auctor mattis at at diam. Sed at rutrum nisl. Quisque tempus, arcu vel molestie aliquam, augue enim tempor odio, eu malesuada tortor lacus quis nisi. Integer ut mollis sapien. Duis pellentesque leo pretium pretium egestas. Pellentesque a luctus mi, sit amet ornare erat.\n \nEtiam commodo pharetra accumsan. Nunc cursus massa leo, et tempus massa feugiat eu.",
    reviews: [
      { name: "Reviewer 1", image: "/jpg/fallback.jpg", status: "Bergabung sejak 2016", content: "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Aenean ut lectus dui. Nullam vulputate commodo euismod. In sodales imperdiet nisl vel scelerisque. " },
      { name: "Reviewer 2", image: "/jpg/fallback.jpg", status: "Bergabung sejak 2016", content: "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Aenean ut lectus dui. Nullam vulputate commodo euismod. In sodales imperdiet nisl vel scelerisque. " },
      { name: "Reviewer 3", image: "/jpg/fallback.jpg", status: "Bergabung sejak 2016", content: "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Aenean ut lectus dui. Nullam vulputate commodo euismod. In sodales imperdiet nisl vel scelerisque. " },
    ],
  },
  {
    id: "2",
    image: "https://via.placeholder.com/150",
    name: "Jane Smith",
    location: "Los Angeles, CA",
    rating_total: "4.8",
    tags: [{ label: "Piano" }, { label: "Intermediate" }],
    short: "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Aenean ut lectus dui. Nullam vulputate commodo euismod. In sodales imperdiet nisl vel scelerisque.",
    bio: "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Aenean ut lectus dui. Nullam vulputate commodo euismod. In sodales imperdiet nisl vel scelerisque. Duis venenatis fermentum lacinia. Quisque in porta dui, vel dictum odio. Phasellus ac tellus non neque pellentesque laoreet.\n \nAenean sit amet elit sit amet sem ornare blandit. Quisque in augue id ligula auctor mattis at at diam. Sed at rutrum nisl. Quisque tempus, arcu vel molestie aliquam, augue enim tempor odio, eu malesuada tortor lacus quis nisi. Integer ut mollis sapien. Duis pellentesque leo pretium pretium egestas. Pellentesque a luctus mi, sit amet ornare erat.\n \nEtiam commodo pharetra accumsan. Nunc cursus massa leo, et tempus massa feugiat eu.",
    reviews: [
      { name: "Reviewer 1", image: "/jpg/fallback.jpg", status: "Bergabung sejak 2016", content: "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Aenean ut lectus dui. Nullam vulputate commodo euismod. In sodales imperdiet nisl vel scelerisque. " },
      { name: "Reviewer 2", image: "/jpg/fallback.jpg", status: "Bergabung sejak 2016", content: "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Aenean ut lectus dui. Nullam vulputate commodo euismod. In sodales imperdiet nisl vel scelerisque. " },
      { name: "Reviewer 3", image: "/jpg/fallback.jpg", status: "Bergabung sejak 2016", content: "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Aenean ut lectus dui. Nullam vulputate commodo euismod. In sodales imperdiet nisl vel scelerisque. " },
    ],
  },
  {
    id: "3",
    image: "https://via.placeholder.com/150",
    name: "Michael Johnson",
    location: "Chicago, IL",
    rating_total: "4.6",
    tags: [{ label: "Violin" }, { label: "Advanced" }],
    short: "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Aenean ut lectus dui. Nullam vulputate commodo euismod. In sodales imperdiet nisl vel scelerisque.",
    bio: "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Aenean ut lectus dui. Nullam vulputate commodo euismod. In sodales imperdiet nisl vel scelerisque. Duis venenatis fermentum lacinia. Quisque in porta dui, vel dictum odio. Phasellus ac tellus non neque pellentesque laoreet.\n \nAenean sit amet elit sit amet sem ornare blandit. Quisque in augue id ligula auctor mattis at at diam. Sed at rutrum nisl. Quisque tempus, arcu vel molestie aliquam, augue enim tempor odio, eu malesuada tortor lacus quis nisi. Integer ut mollis sapien. Duis pellentesque leo pretium pretium egestas. Pellentesque a luctus mi, sit amet ornare erat.\n \nEtiam commodo pharetra accumsan. Nunc cursus massa leo, et tempus massa feugiat eu.",
    reviews: [
      { name: "Reviewer 1", image: "/jpg/fallback.jpg", status: "Bergabung sejak 2016", content: "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Aenean ut lectus dui. Nullam vulputate commodo euismod. In sodales imperdiet nisl vel scelerisque. " },
      { name: "Reviewer 2", image: "/jpg/fallback.jpg", status: "Bergabung sejak 2016", content: "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Aenean ut lectus dui. Nullam vulputate commodo euismod. In sodales imperdiet nisl vel scelerisque. " },
      { name: "Reviewer 3", image: "/jpg/fallback.jpg", status: "Bergabung sejak 2016", content: "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Aenean ut lectus dui. Nullam vulputate commodo euismod. In sodales imperdiet nisl vel scelerisque. " },
    ],
  },
  {
    id: "4",
    image: "https://via.placeholder.com/150",
    name: "Emily Davis",
    location: "Austin, TX",
    rating_total: "4.7",
    tags: [{ label: "Drums" }, { label: "Beginner" }],
    short: "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Aenean ut lectus dui. Nullam vulputate commodo euismod. In sodales imperdiet nisl vel scelerisque.",
    bio: "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Aenean ut lectus dui. Nullam vulputate commodo euismod. In sodales imperdiet nisl vel scelerisque. Duis venenatis fermentum lacinia. Quisque in porta dui, vel dictum odio. Phasellus ac tellus non neque pellentesque laoreet.\n \nAenean sit amet elit sit amet sem ornare blandit. Quisque in augue id ligula auctor mattis at at diam. Sed at rutrum nisl. Quisque tempus, arcu vel molestie aliquam, augue enim tempor odio, eu malesuada tortor lacus quis nisi. Integer ut mollis sapien. Duis pellentesque leo pretium pretium egestas. Pellentesque a luctus mi, sit amet ornare erat.\n \nEtiam commodo pharetra accumsan. Nunc cursus massa leo, et tempus massa feugiat eu.",
    reviews: [
      { name: "Reviewer 1", image: "/jpg/fallback.jpg", status: "Bergabung sejak 2016", content: "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Aenean ut lectus dui. Nullam vulputate commodo euismod. In sodales imperdiet nisl vel scelerisque. " },
      { name: "Reviewer 2", image: "/jpg/fallback.jpg", status: "Bergabung sejak 2016", content: "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Aenean ut lectus dui. Nullam vulputate commodo euismod. In sodales imperdiet nisl vel scelerisque. " },
      { name: "Reviewer 3", image: "/jpg/fallback.jpg", status: "Bergabung sejak 2016", content: "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Aenean ut lectus dui. Nullam vulputate commodo euismod. In sodales imperdiet nisl vel scelerisque. " },
    ],
  },
  {
    id: "5",
    image: "https://via.placeholder.com/150",
    name: "David Brown",
    location: "Seattle, WA",
    rating_total: "4.9",
    tags: [{ label: "Voice" }, { label: "All Levels" }],
    short: "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Aenean ut lectus dui. Nullam vulputate commodo euismod. In sodales imperdiet nisl vel scelerisque.",
    bio: "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Aenean ut lectus dui. Nullam vulputate commodo euismod. In sodales imperdiet nisl vel scelerisque. Duis venenatis fermentum lacinia. Quisque in porta dui, vel dictum odio. Phasellus ac tellus non neque pellentesque laoreet.\n \nAenean sit amet elit sit amet sem ornare blandit. Quisque in augue id ligula auctor mattis at at diam. Sed at rutrum nisl. Quisque tempus, arcu vel molestie aliquam, augue enim tempor odio, eu malesuada tortor lacus quis nisi. Integer ut mollis sapien. Duis pellentesque leo pretium pretium egestas. Pellentesque a luctus mi, sit amet ornare erat.\n \nEtiam commodo pharetra accumsan. Nunc cursus massa leo, et tempus massa feugiat eu.",
    reviews: [
      { name: "Reviewer 1", image: "/jpg/fallback.jpg", status: "Bergabung sejak 2016", content: "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Aenean ut lectus dui. Nullam vulputate commodo euismod. In sodales imperdiet nisl vel scelerisque. " },
      { name: "Reviewer 2", image: "/jpg/fallback.jpg", status: "Bergabung sejak 2016", content: "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Aenean ut lectus dui. Nullam vulputate commodo euismod. In sodales imperdiet nisl vel scelerisque. " },
      { name: "Reviewer 3", image: "/jpg/fallback.jpg", status: "Bergabung sejak 2016", content: "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Aenean ut lectus dui. Nullam vulputate commodo euismod. In sodales imperdiet nisl vel scelerisque. " },
    ],
  },
];
