name: Rhapsodie V2

on:
  push:
    branches:
      - master

jobs:
  web-deploy:
    name: Deploy on Master
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [20.12.1]

    steps:
      - name: Get latest code
        uses: actions/checkout@v2

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@master
        with:
          node-version: ${{ matrix.node-version }}

      - name: Copying environment variables
        run: cp .env.prod.example .env

      - name: Installing required packages
        run: npm install

      - name: Builds the app for production
        run: CI= npm run build

      - name: List output files
        run: find build/ -print

      - name: Sync files
        uses: SamKirkland/FTP-Deploy-Action@4.3.3
        with:
          server: ${{ secrets.FTP_HOST }}
          username: ${{ secrets.FTP_USERNAME }}
          password: ${{ secrets.FTP_PASSWORD }}
          local-dir: build/
